#!/bin/sh
#
# Runs when the learner clicks Skip.
#
# NOTE: AWS onboarding can't be done from a script - it requires a
# real CloudFormation stack run in the AWS Console. This is a stub so
# Skip is at least available and doesn't error; it does NOT actually
# onboard the AWS account or create the ringfence ruleset.

exit 0
