#!/bin/sh

# Force AWS region
export AWS_REGION=us-east-1
export AWS_DEFAULT_REGION=us-east-1

git clone https://github.com/Illumio-Training-Org/26x-course.git
cd 26x-course/terraform

# Add HashiCorp GPG key
curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

# Add HashiCorp apt repo
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list

# Update ONLY HashiCorp repo to speed it up
apt-get update -o Dir::Etc::sourcelist="sources.list.d/hashicorp.list" \
               -o Dir::Etc::sourceparts="-" \
               -o APT::Get::List-Cleanup="0"

# Install Terraform
apt-get install -y terraform

# Configure Terraform
terraform init -input=false
terraform plan -out=tfplan -input=false
terraform apply -input=false -auto-approve tfplan

# Configure SSH
cp my-keypair.pem /root/.ssh/
