#!/bin/sh
#
# This script runs when the platform checks the challenge.
# The platform determines success using this script's exit code.
# Exit 0 = pass, non-zero = fail.
#
# TODO: not yet implemented - task objective not yet decided.

echo "TODO: check not yet implemented for this task"

exit 1
