#!/bin/bash
# Regenerates track_scripts/setup-cloud-client from html/*.html.
# Run this after any change to the HTML, then `instruqt track push`.
# The page is embedded in the setup script (no download at lab start),
# so the track has no runtime dependency on GitHub or OneDrive.
set -euo pipefail
cd "$(dirname "$0")"
SRC=html/Illumio-PCE-Pairing-Lab-Offline.html
OUT=track_scripts/setup-cloud-client
{
  cat <<'HEAD'
#!/bin/bash
# GENERATED by build-setup.sh - do not edit by hand; edit html/ and rebuild.
# Serves the offline PCE pairing simulation on cloud-client:80 (the
# image's built-in web server root, same as ! 26.x Lab's welcome page).
set -euo pipefail
mkdir -p /var/www/html
base64 -d > /var/www/html/index.html <<'PCE_HTML_B64'
HEAD
  base64 < "$SRC" | fold -w 76
  cat <<'TAIL'
PCE_HTML_B64
# Same page for every tab; it picks Console or terminal mode from its file name
for n in linux windows aix; do cp /var/www/html/index.html /var/www/html/$n.html; done
echo "System PCE pages installed: $(wc -c < /var/www/html/index.html) bytes each"
TAIL
} > "$OUT"
chmod +x "$OUT"
echo "Wrote $OUT ($(wc -c < "$OUT") bytes)"
