#!/bin/bash
# Regenerates track_scripts/setup-cloud-client from html/*.html.
# Run this after any change to the HTML, then `instruqt track push`.
# The page is embedded in the setup script (no download at lab start),
# so the track has no runtime dependency on GitHub or OneDrive.
set -euo pipefail
cd "$(dirname "$0")"
SRC=html/Illumio-PCE-Pairing-Lab-Offline.html
OUT=track_scripts/setup-cloud-client
{
  cat <<'HEAD'
#!/bin/bash
# GENERATED by build-setup.sh - do not edit by hand; edit html/ and rebuild.
# Installs the four tab pages and the small web server (server/server.py)
# that serves them on cloud-client:8080 and records paired workloads in
# /root/pce-lab-state.json for the challenge check script.
set -euo pipefail
mkdir -p /var/www/pce-lab /opt/pce-lab
base64 -d > /var/www/pce-lab/index.html <<'PCE_HTML_B64'
HEAD
  base64 < "$SRC" | fold -w 76
  cat <<'TAIL'
PCE_HTML_B64
# Same page for every tab; it picks Console or terminal mode from its file name
for n in linux windows aix; do cp /var/www/pce-lab/index.html /var/www/pce-lab/$n.html; done
echo "System PCE pages installed: $(wc -c < /var/www/pce-lab/index.html) bytes each"
cat > /opt/pce-lab/server.py <<'PCE_SERVER_PY'
TAIL
  cat server/server.py
  cat <<'TAIL2'
PCE_SERVER_PY
echo '{"workloads": []}' > /root/pce-lab-state.json
setsid nohup python3 /opt/pce-lab/server.py > /var/log/pce-lab-server.log 2>&1 < /dev/null &
for i in $(seq 1 30); do
  if curl -fsS -o /dev/null http://localhost:8080/; then echo "pce-lab server up on :8080"; exit 0; fi
  sleep 1
done
echo "pce-lab server did not start:"; cat /var/log/pce-lab-server.log; exit 1
TAIL2
} > "$OUT"
chmod +x "$OUT"
echo "Wrote $OUT ($(wc -c < "$OUT") bytes)"
